### PR TITLE
refactor(paths): change path for `themes`

### PR DESCRIPTION
**Pull request by adnasa**
breaking change
Let me know which packages besides `dext` itself is affected by this

### CODE REVIEW

**Comment by adnasa** [comment]
oh... I'm collaborator on this project too.. I didn't know that 😛

**Comment by adnasa** [comment]
Considering how `dext-cli` works and installs packages, this can actually open up a can of worms. I still think we should go through with this PR, even if this doesn't have to happen now since there are other more pressing issues to address

**Comment by adnasa** [comment]
wait.... `dext-cli` uses `dext-core-utils` to install themes? 😂 
ref: https://github.com/vutran/dext-core-utils/blob/develop/src/api/index.js#L28

**Review by vutran — APPROVED** [review]

**Comment by vutran** [comment]
Yeah, I think we should start merging core utils and CLI (maybe even get rid of CLI eventually) into a monorepo with lerna

**Comment by adnasa** [comment]
Hah!! I knew you would need some time to be convinced!

**Comment by adnasa** [comment]
For obvious reasons, this is now of low priority. I'll close this

**Pull request closed without merging**
